---
name: Publish-Release

# Run this workflow every time a new release is published
on:
    release:
        types: [released]

permissions: read-all

jobs:
    publish-release:
        name: Publish release to Foundry
        runs-on: ubuntu-latest
    
        steps:
          - name: POST release
            id: myRequest
            uses: fjogeleit/http-request-action@v1
            with:
                url: 'https://api.foundryvtt.com/_api/packages/release_version/'
                method: 'POST'
                customHeaders: '{"Authorization": "${{ secrets.FOUNDRY_API_TOKEN }}"}'
                data: 
                    '{
                        "id": "settlement-sheets",
                        "release": {
                            "version": "${{ github.event.release.tag_name }}",
                            "manifest": "https://github.com/veilza/settlement-sheets/releases/download/${{ github.event.release.tag_name }}/module.json",
                            "notes": "https://github.com/veilza/settlement-sheets/releases/tag/${{ github.event.release.tag_name }}",
                            "compatibility": {
                                "minimum": "12",
                                "verified": "12.328",
                                "maximum": ""
                            }
                        }
                    }'
